# wydoujin — local dev via Docker
#
# The app runs in containers (app + MySQL) from the existing docker-compose.yml,
# so the broken host PHP is never touched. Compose reads .env.docker (generated by
# `make init`) instead of .env, so it won't pick up the host's sqlite DB_CONNECTION.
# Tests run in a separate throwaway container (docker/test.Dockerfile, SQLite
# :memory:) so the production image keeps NO dev deps.
#
# Quick start:
#   make init          # one-time: write .env.docker (generated keys) + ./library
#   make start         # build, start app+mysql, wait for db, migrate
#   open http://localhost:8080
#   make test          # run the suite in Docker

COMPOSE  := docker compose --env-file .env.docker
APP      := app
TEST_IMG := wydoujin:test
VENDOR_VOL := wydoujin_vendor
NODE_VOL := wydoujin_node
NPM_CACHE_VOL := wydoujin_npmcache

.DEFAULT_GOAL := help

.PHONY: help init ensure-env start up build down restart reset ps logs shell \
        migrate fresh artisan key assets test test-image test-filter clean nuke

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

## ----- First-time setup -----

# A standard Laravel .env (sqlite) for the test container + any host use. It is
# git-ignored AND excluded by .dockerignore, so the running app (which reads
# .env.docker via --env-file) never sees it.
ensure-env:
	@if [ ! -f .env ]; then \
		cp .env.example .env; \
		sed -i.bak "s|^APP_KEY=.*|APP_KEY=base64:$$(openssl rand -base64 32)|" .env && rm -f .env.bak; \
		echo "Created .env (sqlite; for host/test use only)"; fi

init: ensure-env ## Write .env / .env.docker (generated keys) and ./testdata; run once
	@if [ -f .env.docker ]; then echo ".env.docker already exists — leaving it untouched"; else \
		printf '%s\n' \
			"APP_KEY=base64:$$(openssl rand -base64 32)" \
			"APP_PASSWORD=" \
			"QUEUE_WORKERS=1" \
			"DB_CONNECTION=mysql" \
			"DB_HOST=mysql" \
			"DB_PORT=3306" \
			"DB_DATABASE=wydoujin" \
			"DB_USERNAME=wydoujin" \
			"DB_PASSWORD=$$(openssl rand -hex 16)" \
			"DB_ROOT_PASSWORD=$$(openssl rand -hex 16)" \
			"LIBRARY_PATH=./testdata" \
			> .env.docker; \
		echo "Wrote .env.docker"; fi
	@mkdir -p testdata
	@echo "Drop test data in ./testdata/<mangaka>/<name>.zip, then: make start"

## ----- Run the app (containers) -----

start: up ## Build+start app & MySQL, wait for the db, then migrate
	@echo "Waiting for MySQL to accept connections..."
	@until $(COMPOSE) exec -T mysql mysqladmin ping -h 127.0.0.1 --silent >/dev/null 2>&1; do sleep 2; done
	@$(MAKE) migrate
	@echo "Ready → http://localhost:8080"

up: ## Start app + MySQL in the background (builds the image if needed)
	$(COMPOSE) up -d --build

build: ## Build the app image only
	$(COMPOSE) build

down: ## Stop and remove the app + MySQL containers (keeps volumes/data)
	$(COMPOSE) down

restart: ## Restart the app container (keeps its env; won't pick up .env.docker edits)
	$(COMPOSE) restart $(APP)

reset: ## Recreate the app container so .env.docker changes (e.g. APP_PASSWORD) take effect
	$(COMPOSE) up -d --force-recreate $(APP)

ps: ## Show container status
	$(COMPOSE) ps

logs: ## Follow logs from all containers
	$(COMPOSE) logs -f

shell: ## Open a shell inside the app container
	$(COMPOSE) exec $(APP) bash

## ----- Database / artisan (inside the app container) -----

migrate: ## Apply migrations in the app container
	$(COMPOSE) exec $(APP) php artisan migrate --force

fresh: ## Drop all tables and re-migrate (wipes the dev MySQL data)
	$(COMPOSE) exec $(APP) php artisan migrate:fresh --force

artisan: ## Run any artisan command: make artisan CMD="route:list"
	$(COMPOSE) exec $(APP) php artisan $(CMD)

key: ## Print a fresh APP_KEY you can paste into .env.docker
	@echo "base64:$$(openssl rand -base64 32)"

## ----- Tests (separate throwaway container, SQLite :memory:) -----

test-image: ## Build the test-runner image
	docker build -f docker/test.Dockerfile -t $(TEST_IMG) .

assets: ## Build frontend assets in a node container (needed by view-rendering tests)
	docker run --rm -v "$(CURDIR)":/app -w /app \
		-v $(NODE_VOL):/app/node_modules -v $(NPM_CACHE_VOL):/root/.npm \
		node:22-alpine sh -lc "npm ci --no-audit --no-fund && npm run build"

TEST_RUN = docker run --rm -v "$(CURDIR)":/app -v $(VENDOR_VOL):/app/vendor $(TEST_IMG)

test: test-image assets ensure-env ## Run the full Pest suite in Docker
	$(TEST_RUN) sh -lc "composer install --no-interaction --no-progress && php artisan test"

test-filter: test-image assets ensure-env ## Run a subset: make test-filter FILTER=health
	$(TEST_RUN) sh -lc "composer install --no-interaction --no-progress && vendor/bin/pest --filter=$(FILTER)"

## ----- Cleanup -----

clean: ## Stop containers and remove the app/test images
	-$(COMPOSE) down
	-docker image rm $(TEST_IMG) wydoujin:dev 2>/dev/null || true

nuke: ## clean + delete all volumes (DB, cover cache, vendor + node cache) — destructive
	-$(COMPOSE) down -v
	-docker volume rm $(VENDOR_VOL) $(NODE_VOL) $(NPM_CACHE_VOL) 2>/dev/null || true
